### PR TITLE
Gradle 7.6, Update Actions and fabric-loader.

### PR DESCRIPTION
**Pull request by Kichura**
Updates the GitHub Actions to make comments look a little better; Upstreams the upload-artifact to v3 which includes ubuntu being upstreamed to 22.04 in syncing configuration,

Also upstreams the fabric loader to be on 0.14.12 instead along with Gradle being on 7.6 which adds support for JDK 19 when self-compiling.

### CODE REVIEW

**Review by Aizistral — APPROVED** [review]

**Comment by Aizistral** [comment]
Unfortunately it doesn't look like the project is buildable with Gradle 7.6: https://github.com/Aizistral-Studios/No-Chat-Reports/actions/runs/3825701114/jobs/6508900982
I guess we'll have to live with 7.4 for a while longer.

**Comment by Kichura** [comment]
Or use gradle 7.5.1 perhaps?

**Comment by Aizistral** [comment]
If it builds 🤷 https://github.com/Aizistral-Studios/No-Chat-Reports/actions/runs/3825746869/jobs/6508957371

**Comment by Aizistral** [comment]
Alright, it seems to work, so the answer is yes.

**Comment by Kichura** [comment]
that has worked lol.

**Pull request merged**
