### PR TITLE
Groundwork for Mod Menu support, If I didn't fuck this up

### PR DESCRIPTION
**Pull request by MODKILLER1001**
add modconfig, modmenuintegration, edited fabric.mod.json

### CODE REVIEW

**Comment by Aizistral** [comment]
How is that supposed to work with existing .json config? For reference, we cannot give up on that because I want config file to look the same between Forge and Fabric.

**Comment by mrrpmrreeoow** [comment]
also please add cloth config support :)

**Comment by MODKILLER1001** [comment]
> 

I am not sure, I might not be smart enough to do this.

**Comment by MODKILLER1001** [comment]
If anyone else would like to tackle this I would really appreciate it.

**Comment by MODKILLER1001** [comment]
$5 dollar bounty or discord nitro if anyone can get this added and have it not break forge.

**Comment by MODKILLER1001** [comment]
I think this might work as it isnt crashing but I am still having issues trying to make mod menu gui work

**Comment by MODKILLER1001** [comment]
Now is working.

**Comment by MODKILLER1001** [comment]
Config is now saving but you need to reload to see changes, working on that next.

**Comment by MODKILLER1001** [comment]
Everything is working expect the fact that you need to reload your game each time you change a config in mod menu, could someone please help. @Madis0 this might be up your alley to look into.

**Pull request closed without merging**
