### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by IlyaYezelovsky**
Deleted spaces and added missing strings.

### CODE REVIEW

**Comment by GodGun968** [comment]
gui.nochatreports.encryption_warning.contents中的值和原英文不一样，而且gui.nochatreports.encryption_warning.learn_more中的值是了解更多，所以gui.nochatreports.encryption_warning.contents中的"learn more"的翻译应该是“了解更多”而不是“了解更多信息”

**Comment by GodGun968** [comment]
有的文本在"en_us.json"文件里已经被移除了,没必要再加回来
有的文本与"en_us.json"未保持一致

**Comment by GodGun968** [comment]
有的文本在"en_us.json"文件里已经被移除了,没必要再加回来
有的文本的翻译与"en_us.json"未保持一致
在我提交的那一个拉取请求大部分问题已经被修复了
建议你根据我提交的那一版重新更改

**Comment by GodGun968** [comment]
@Aizistral I propose to withdraw the merge of this pull request

**Comment by Aizistral** [comment]
> @Aizistral I propose to withdraw the merge of this pull request

Can you elaborate? I cannot audit this translation myself, but I am open to feedback.

**Comment by GodGun968** [comment]
> Can you elaborate? I cannot audit this translation myself, but I am open to feedback.

The reason is above, if you don't mind, you can use Google Translate to view, of course, I can also provide you with English

**Comment by GodGun968** [comment]
@Aizistral What do you think?

**Comment by GodGun968** [comment]
Now, It seems to be error-free

**Comment by GodGun968** [comment]
@Aizistral It does have problems, some texts that have been translated are deleted by mistake, and some texts are useless (Text that no longer exists in "en_us.json") was added back. Some translations that had been corrected were reverted

**Pull request merged**
