### PR TITLE
Add NeoForge project

### PR DESCRIPTION
**Pull request by embeddedt**
Does what it says on the tin. The project structure is exactly the same as Forge (with symlinks and all), only real change is using NeoGradle 7 instead of ForgeGradle and obviously some package renames.

I also removed the `sourceSets.remove(sourceSets.test)` lines to fix IntelliJ IDEA refusing to import the project. These seemed unnecessary.

### CODE REVIEW

**Comment by mrjasonn** [comment]
Might be a good idea to make this mod use Architectrury for multi platform development at the same time?

**Comment by embeddedt** [comment]
That is a good idea, but IMO it is out of scope and should be done in a separate PR, as it will be a much larger change. I don't think the few extra files this project adds will make it much harder to convert to Architectury in the future.

**Review by Madis0 — APPROVED** [review]
Successfully compiled Fabric on Intellij IDEA, so that's already an improvement to me :grin: Didn't figure out how to run Forge and NeoForge variants, but I assume they work as well.

**Review by Aizistral — APPROVED** [review]
It worky 👍

**Comment by Aizistral** [comment]
> Might be a good idea to make this mod use Architectrury for multi platform development at the same time?

Regarding Architectury. I tried it in the past, and the issue with it is that it basically isn't compatible with Eclipse IDE, which is the IDE I'm using. Besides, I feel using it would bring unnecessary dependencies into the project. Current setup is a little hacky, but it offers superior end user experience, imo.

**Pull request merged**
