### PR TITLE
You don't need the entire Fabric API

### LINKED ISSUE #16: Is it possible to make this mod standalone
As the title, is it possible to make this mod runs alone without a mod api, just like how optifine works?

### PR DESCRIPTION
**Pull request by LoganDark**
This massively speeds up sync times for me, since Loom no longer has to remap 45+ Fabric API modules. Additionally, this allows users to install No Chat Reports without Fabric API, as the required modules are already included.

### CODE REVIEW

**Comment by Madis0** [comment]
Considering #131 plans to add a Cloth Config dependency anyway, I don't see how losing Fabric API dependency would benefit :sweat_smile:

**Comment by LoganDark** [comment]
This isn't losing the entire dependency (btw, Cloth Config ~~only requires the screens API iirc~~ v6 doesn't require Fabric API at all) it's just being more precise so that No Chat Reports only requires what it *actually* depends on.

Basically No Chat Reports only uses certain *parts* of Fabric API, not every single module, so this PR specifies which modules it actually uses, so that you don't have to include all 45+ modules (which speeds up build/sync times very nicely).

**Comment by Madis0** [comment]
Does it also bundle these parts of the API in the JAR, or does it just change the dev environment?

**Comment by LoganDark** [comment]
Yes, it does bundle those parts in the jar. Fabric Loader will do dependency resolution across all mods that bundle a certain module, and pick the newest version, so this is fine.

**Comment by LoganDark** [comment]
P.S. the jar generated from the build is still only 87 KB. So the fabric API modules don't seem to make it prohibitively large.

**Comment by ghost** [comment]
that's actually what Sodium does and I'm looking forwardto ncr bundling fapi modules jar in jar

**Comment by LoganDark** [comment]
Hey @Aizistral, once I fix these merge conflicts, could you try to get this merged before any more pop up?

**Comment by Aizistral** [comment]
Sure. I finally got around reviewing those three PRs, so you can expect your to be merged today if everything is fine.

**Review by Aizistral — APPROVED** [review]
> P.S. the jar generated from the build is still only 87 KB. So the fabric API modules don't seem to make it prohibitively large.

As far as I can tell it's 373 KB. Still not prohibitively large though.

> Fabric Loader will do dependency resolution across all mods that bundle a certain module, and pick the newest version, so this is fine.

I didn't even know it works this way, which is why I was initially skeptical towards this PR. But as far as I can tell from my tests - you are right. If bunding API is not an uncommon practice - then I don't see a reason to not merge this, especially considering the amount of people that complained about the game not booting up because they didn't know that loader means Fabric API when it wants `fabric` from them.

**Pull request merged**
