### PR TITLE
1.20.5

### PR DESCRIPTION
**Pull request by Madis0**
Didn't get to the remapping part because
> A problem occurred evaluating project ':Forge'.
> Failed to apply plugin 'net.minecraftforge.gradle'.
   Could not create an instance of type net.minecraftforge.gradle.userdev.DependencyManagementExtension.
      Could not find 'versionParser'

but I guess it could help you nonetheless

### CODE REVIEW

**Comment by Aizistral** [comment]
You need to disable Forge/NeoForge subprojects altogether if you want to work with snapshots or pre-releases. Iirc only Fabric supports these.

**Comment by Aizistral** [comment]
Checks can't pass because the base repo is still using Java 17, but now things may work locally.

**Comment by Quillbert** [comment]
I think there may still be a few more kinks to workout. When I try to build this version with `./gradlew build`, I get this mixin error: 
```
> Task :compileJava
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/server/MixinServerboundChatCommandPacket.java:20: warning: Unable to determine descriptor for @Inject target method
        @Inject(method = "argumentSignatures", at = @At("RETURN"), cancellable = true)
        ^
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinTitleScreen.java:23: warning: Unable to determine descriptor for @Inject target method
        @Inject(method = "realmsButtonClicked", at = @At("HEAD"), cancellable = true)
        ^
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinChatComponent.java:54: warning: Cannot find target method "addMessage(Lnet/minecraft/network/chat/Component;Lnet/minecraft/network/chat/MessageSignature;ILnet/minecraft/client/GuiMessageTag;Z)V" for @ModifyArg.method="addMessage(Lnet/minecraft/network/chat/Component;Lnet/minecraft/network/chat/MessageSignature;ILnet/minecraft/client/GuiMessageTag;Z)V" in net.minecraft.client.gui.components.ChatComponent
        @ModifyArg(index = 0, method = "addMessage(Lnet/minecraft/network/chat/Component;"
        ^
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinChatComponent.java:35: warning: Cannot find target method "addMessage(Lnet/minecraft/network/chat/Component;Lnet/minecraft/network/chat/MessageSignature;ILnet/minecraft/client/GuiMessageTag;Z)V" for @ModifyVariable.method="addMessage(Lnet/minecraft/network/chat/Component;Lnet/minecraft/network/chat/MessageSignature;ILnet/minecraft/client/GuiMessageTag;Z)V" in net.minecraft.client.gui.components.ChatComponent
        @ModifyVariable(method = "addMessage(Lnet/minecraft/network/chat/Component;"
        ^
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/server/MixinServerCommonPacketListenerImpl.java:47: error: cannot find symbol
                                        packet = new ClientboundSystemChatPacket(chat.chatType().resolve(listener.player.level()
                                                                                                ^
  symbol:   method resolve(RegistryAccess)
  location: class Bound
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinChatComponent.java:62: error: method toJson in class Serializer cannot be applied to given types;
                                        Component.Serializer.toJson((Component) msg));
                                                            ^
  required: Component,Provider
  found:    Component
  reason: actual and formal argument lists differ in length
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinOnlineServerEntry.java:55: error: cannot find symbol
                                this.screen.setToolTip(FontHelper.wrap(this.minecraft.font, Language.getInstance()
                                           ^
  symbol:   method setToolTip(ArrayList<Component>)
  location: variable screen of type JoinMultiplayerScreen
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinChatListener.java:105: error: method toJson in class Serializer cannot be applied to given types;
                                        Component.Serializer.toJson(playerChatMessage.unsignedContent()),
                                                            ^
  required: Component,Provider
  found:    Component
  reason: actual and formal argument lists differ in length
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/common/MixinFriendlyByteBuf.java:40: error: cannot find symbol
                        Object result = Util.getOrThrow(dataResult, string -> new DecoderException("Failed to decode json: " + string));
                                            ^
  symbol:   method getOrThrow(DataResult,(string)->[...]ring))
  location: class Util
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/mixins/common/MixinFriendlyByteBuf.java:60: error: cannot find symbol
                        JsonElement element = Util.getOrThrow(dataResult, string -> new EncoderException("Failed to encode: " + string + " " + object));
                                                  ^
  symbol:   method getOrThrow(DataResult<JsonElement>,(string)->[...]ject))
  location: class Util
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/gui/AdvancedTooltip.java:140: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/gui/AdvancedTooltip.java:142: error: cannot find symbol
                return super.createTooltipPositioner(hovered, focused, rectangle);
                            ^
  symbol: method createTooltipPositioner(boolean,boolean,ScreenRectangle)
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/gui/AdvancedTooltip.java:145: error: method does not override or implement a method from a supertype
        @Override // ideally tooltip shouldn't control it's own render like this, but for now it does
        ^
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/gui/AdvancedTooltip.java:150: error: cannot find symbol
                super.refreshTooltipForNextRenderPass(hovered, focused, screenRectangle);
                     ^
  symbol: method refreshTooltipForNextRenderPass(boolean,boolean,ScreenRectangle)
/home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/core/EncryptionUtil.java:75: error: method toJson in class Serializer cannot be applied to given types;
                return Component.Serializer.fromJson(Component.Serializer.toJson(component));
                                                                         ^
  required: Component,Provider
  found:    Component
  reason: actual and formal argument lists differ in length
Note: /home/andrew/NCR/src/main/java/com/aizistral/nochatreports/common/gui/AdvancedTooltip.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
4 warnings

> Task :compileJava FAILED

FAILURE: Build failed with an exception.
```

**Comment by Madis0** [comment]
You're right, there are at least 11 unfixed mixin errors right now. Feel free to contribute.

**Comment by Quillbert** [comment]
I've spent a couple of hours trying to fix this and update to 1.20.6, but I think I might have bitten off a bit more than I can chew😅.

Most of my efforts were spent trying to update from the main branch rather than this PR, so it is possible I missed something.

My best guess at the cause of the error is that the Mixin library is not being recognized by the build system. I have tried compiling with Forge and NeoForge disabled, with both enabled, and with only Forge enabled. I also updated every version number I could find in the Gradle config files to the most up to date versions I could find, but none of that seemed to work. My inexperience with Gradle is holding me back a bit I think, but I'll keep looking and submit I PR if I ever manage to get it working.

**Comment by Madis0** [comment]
https://github.com/Aizistral-Studios/No-Chat-Reports/commit/93431ded9ec631d9ef1c25084b567efe66e070d9

**Pull request closed without merging**
