### PR TITLE
Use gradle 7.5

### PR DESCRIPTION
**Pull request by localfossa**
New version came out 8 days ago.

### CODE REVIEW

**Comment by Aizistral** [comment]
What difference does it make?

**Comment by localfossa** [comment]
> What difference does it make?

https://docs.gradle.org/7.5/release-notes.html

**Comment by localfossa** [comment]
> What difference does it make?

Will you merge this or not?

**Comment by Aizistral** [comment]
I decided not to until Fabric's example mod setup updates it as well: https://github.com/FabricMC/fabric-example-mod/blob/1.19/gradle/wrapper/gradle-wrapper.properties

My experience with Gradle tells me that each update has great potential to break things.

**Pull request closed without merging**
