### PR TITLE
Adds support for ModMenu

### PR DESCRIPTION
**Pull request by MODKILLER1001**

### CODE REVIEW

**Comment by MODKILLER1001** [comment]
Forgot to add description when making PR, this is ready to merge.

**Comment by MODKILLER1001** [comment]
Add categories in commit 16a627b 
image
image

**Comment by ghost** [comment]
A cloth config dependency would be TERRIBLE for a mod everyone would want to install. I don't want NCR as the only mod in my mod folder that needs that huge external dependency.

Please make the dependency optional.

**Comment by DioEgizio** [comment]
what about just JiJing it

**Comment by MODKILLER1001** [comment]
It still runs without cloth config, you just don't have mod menu support

**Comment by MODKILLER1001** [comment]
> A cloth config dependency would be TERRIBLE for a mod everyone would want to install. I don't want NCR as the only mod in my mod folder that needs that huge external dependency.
> 
> Please make the dependency optional.

Also in my testing, [https://github.com/Aizistral-Studios/No-Chat-Reports/actions/runs/2782232783](https://github.com/Aizistral-Studios/No-Chat-Reports/actions/runs/2782232783) build 249 still runs without cloth config and mod menu, you just do not have the GUI. I have been running this build for a few days now without issue.

**Comment by LoganDark** [comment]
> what about just JiJing it

This. Please don't require users to install Cloth Config separately.

**Comment by Madis0** [comment]
I don't think JiJing is necessary, because:
* Not all modpacks/setups need a graphical GUI anyway and it continues to work without Cloth Config as well 
* This is also a server-side mod and server-side definitely doesn't need it bundled
* Many modpacks/setups already include Cloth Config in one way or another, so this just makes this mod larger

**Comment by LoganDark** [comment]
> Not all modpacks/setups need a graphical GUI anyway and it continues to work without Cloth Config as well

Ah that makes sense. Yeah, I've made mods before that just don't have the config screen unless Cloth Config is installed. That would work.

**Comment by MODKILLER1001** [comment]
fetch and merge 1.8.3 NCR

**Comment by MODKILLER1001** [comment]
fetch and merge 1.8.4 NCR

**Comment by MODKILLER1001** [comment]
Closing as moving to a 1.19.2 branch

**Pull request closed without merging**
